package forum.entity;
// Generated 2018-1-29 15:42:20 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private Integer mid;
	private Message message;
	private Post post;
	private Users users;
	private String mcontent;
	private Date mpubDate;
	private Set<Message> messages = new HashSet<Message>(0);
	public Integer getMid() {
		return mid;
	}
	public void setMid(Integer mid) {
		this.mid = mid;
	}
	public Message getMessage() {
		return message;
	}
	public void setMessage(Message message) {
		this.message = message;
	}
	public Post getPost() {
		return post;
	}
	public void setPost(Post post) {
		this.post = post;
	}
	public Users getUsers() {
		return users;
	}
	public void setUsers(Users users) {
		this.users = users;
	}
	public String getMcontent() {
		return mcontent;
	}
	public void setMcontent(String mcontent) {
		this.mcontent = mcontent;
	}
	public Date getMpubDate() {
		return mpubDate;
	}
	public void setMpubDate(Date mpubDate) {
		this.mpubDate = mpubDate;
	}
	public Set<Message> getMessages() {
		return messages;
	}
	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}


}
