package forum.entity;
// Generated 2018-1-26 18:02:42 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private int MId;
	private int MUId;
	private Integer MRepId;
	private int MPId;
	private String MContent;
	private Date MPubDate;

	public Message() {
	}

	public Message(int MId, int MUId, int MPId, String MContent, Date MPubDate) {
		this.MId = MId;
		this.MUId = MUId;
		this.MPId = MPId;
		this.MContent = MContent;
		this.MPubDate = MPubDate;
	}

	public Message(int MId, int MUId, Integer MRepId, int MPId, String MContent, Date MPubDate) {
		this.MId = MId;
		this.MUId = MUId;
		this.MRepId = MRepId;
		this.MPId = MPId;
		this.MContent = MContent;
		this.MPubDate = MPubDate;
	}

	public int getMId() {
		return this.MId;
	}

	public void setMId(int MId) {
		this.MId = MId;
	}

	public int getMUId() {
		return this.MUId;
	}

	public void setMUId(int MUId) {
		this.MUId = MUId;
	}

	public Integer getMRepId() {
		return this.MRepId;
	}

	public void setMRepId(Integer MRepId) {
		this.MRepId = MRepId;
	}

	public int getMPId() {
		return this.MPId;
	}

	public void setMPId(int MPId) {
		this.MPId = MPId;
	}

	public String getMContent() {
		return this.MContent;
	}

	public void setMContent(String MContent) {
		this.MContent = MContent;
	}

	public Date getMPubDate() {
		return this.MPubDate;
	}

	public void setMPubDate(Date MPubDate) {
		this.MPubDate = MPubDate;
	}

}
