package forum.entity;
// Generated 2018-1-30 11:11:17 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Post generated by hbm2java
 */
public class Post implements java.io.Serializable {

	private int pid;
	private int puid;
	private String pcontent;
	private Date ppubdate;

	public Post() {
	}

	public Post(int pid, int puid, String pcontent, Date ppubdate) {
		this.pid = pid;
		this.puid = puid;
		this.pcontent = pcontent;
		this.ppubdate = ppubdate;
	}

	public int getpid() {
		return this.pid;
	}

	public void setpid(int pid) {
		this.pid = pid;
	}

	public int getpuid() {
		return this.puid;
	}

	public void setpuid(int puid) {
		this.puid = puid;
	}

	public String getpcontent() {
		return this.pcontent;
	}

	public void setpcontent(String pcontent) {
		this.pcontent = pcontent;
	}

	public Date getppubdate() {
		return this.ppubdate;
	}

	public void setppubdate(Date ppubdate) {
		this.ppubdate = ppubdate;
	}

}
