package forum.entity;
// Generated 2018-1-26 18:02:42 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * Post generated by hbm2java
 */
public class Post implements java.io.Serializable {

	private int PId;
	private int PUId;
	private String PContent;
	private Date PPubDate;

	public Post() {
	}

	public Post(int PId, int PUId, String PContent, Date PPubDate) {
		this.PId = PId;
		this.PUId = PUId;
		this.PContent = PContent;
		this.PPubDate = PPubDate;
	}

	public int getPId() {
		return this.PId;
	}

	public void setPId(int PId) {
		this.PId = PId;
	}

	public int getPUId() {
		return this.PUId;
	}

	public void setPUId(int PUId) {
		this.PUId = PUId;
	}

	public String getPContent() {
		return this.PContent;
	}

	public void setPContent(String PContent) {
		this.PContent = PContent;
	}

	public Date getPPubDate() {
		return this.PPubDate;
	}

	public void setPPubDate(Date PPubDate) {
		this.PPubDate = PPubDate;
	}

}
