package forum.entity;
// Generated 2018-1-26 18:02:42 by Hibernate Tools 5.2.8.Final

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int UId;
	private String UName;
	private int USex;
	private String UProfile;
	private int UAge;

	public Users() {
	}

	public Users(int UId, String UName, int USex, int UAge) {
		this.UId = UId;
		this.UName = UName;
		this.USex = USex;
		this.UAge = UAge;
	}

	public Users(int UId, String UName, int USex, String UProfile, int UAge) {
		this.UId = UId;
		this.UName = UName;
		this.USex = USex;
		this.UProfile = UProfile;
		this.UAge = UAge;
	}

	public int getUId() {
		return this.UId;
	}

	public void setUId(int UId) {
		this.UId = UId;
	}

	public String getUName() {
		return this.UName;
	}

	public void setUName(String UName) {
		this.UName = UName;
	}

	public int getUSex() {
		return this.USex;
	}

	public void setUSex(int USex) {
		this.USex = USex;
	}

	public String getUProfile() {
		return this.UProfile;
	}

	public void setUProfile(String UProfile) {
		this.UProfile = UProfile;
	}

	public int getUAge() {
		return this.UAge;
	}

	public void setUAge(int UAge) {
		this.UAge = UAge;
	}

}
