package forum.entity;
// Generated 2018-1-30 11:11:17 by Hibernate Tools 3.5.0.Final

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private int uid;
	private String uname;
	private int usex;
	private String uprofile;
	private int uage;

	public Users() {
	}

	public Users(int uid, String uname, int usex, int uage) {
		this.uid = uid;
		this.uname = uname;
		this.usex = usex;
		this.uage = uage;
	}

	public Users(int uid, String uname, int usex, String uprofile, int uage) {
		this.uid = uid;
		this.uname = uname;
		this.usex = usex;
		this.uprofile = uprofile;
		this.uage = uage;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public int getUsex() {
		return this.usex;
	}

	public void setUsex(int usex) {
		this.usex = usex;
	}

	public String getUprofile() {
		return this.uprofile;
	}

	public void setUprofile(String uprofile) {
		this.uprofile = uprofile;
	}

	public int getUage() {
		return this.uage;
	}

	public void setUage(int uage) {
		this.uage = uage;
	}

}
