package forum.entity;
// Generated 2018-1-28 15:26:03 by Hibernate Tools 5.2.8.Final

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer uid;
	private String uname;
	private Integer usex;
	private String uprofile;
	private Integer uage;

	public Users() {
	}

	public Integer getUid() {
		return uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUname() {
		return uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public Integer getUsex() {
		return usex;
	}

	public void setUsex(Integer usex) {
		this.usex = usex;
	}

	public String getUprofile() {
		return uprofile;
	}

	public void setUprofile(String uprofile) {
		this.uprofile = uprofile;
	}

	public Integer getUage() {
		return uage;
	}

	public void setUage(Integer uage) {
		this.uage = uage;
	}



}
